{
 "title": "HTTP",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values({job=\"kubernetes-ingresses\"},namespace)"
    }
   },
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values({namespace=~\"$Namespace\",job=\"kubernetes-ingresses\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Endpoint probe duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance)(probe_dns_lookup_time_seconds{job=\"kubernetes-ingresses\",instance=~\"$Endpoint\"})",
     "legendFormat": "{{instance}} DNS lookup time"
    },
    {
     "expr": "sum by (instance)(probe_duration_seconds{job=\"kubernetes-ingresses\",instance=~\"$Endpoint\"})",
     "legendFormat": "{{instance}} probe duration"
    }
   ]
  },
  {
   "title": "$Endpoint status code",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance)(probe_http_status_code{job=\"kubernetes-ingresses\",instance=~\"$Endpoint\"}) == 200",
     "legendFormat": "{{instance}} success"
    },
    {
     "expr": "sum by (instance)(probe_http_status_code{job=\"kubernetes-ingresses\",instance=~\"$Endpoint\"}) != 200",
     "legendFormat": "{{instance}} failure"
    }
   ]
  },
  {
   "title": "Ingress endpoints state",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance,namespace)(probe_http_status_code{job=\"kubernetes-ingresses\",instance=~\".*\"})"
    },
    {
     "expr": "sum by (instance,namespace)(probe_duration_seconds{job=\"kubernetes-ingresses\",instance=~\".*\"})"
    },
    {
     "expr": "(sum by (instance,namespace)(probe_ssl_earliest_cert_expiry{job=\"kubernetes-ingresses\",instance=~\".*\"}) - time()) / 86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,namespace)(avg_over_time(probe_success{job=\"kubernetes-ingresses\",instance=~\".*\"}[7d])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}