{
 "title": "Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "App",
    "query": {
     "query": "label_values({namespace=~\"$Namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$App CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod,container,instance)(rate(container_cpu_usage_seconds_total{container!=\"\"}[1m]) + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0)",
     "legendFormat": "{{pod}} {{container }} {{instance}} usage"
    },
    {
     "expr": "sum by (pod,container)(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kubernetes-pods\"} + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0)",
     "legendFormat": "{{pod}} {{container }} requests"
    },
    {
     "expr": "sum by (pod,container)(kube_pod_container_resource_limits{resource=\"cpu\",job=\"kubernetes-pods\"} + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0)",
     "legendFormat": "{{pod}} {{container }} limit"
    }
   ]
  },
  {
   "title": "$App Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod,container,instance)(rate(container_memory_working_set_bytes{container!=\"\"}[1m]) + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0)",
     "legendFormat": "{{pod}} {{container }} {{ instance }} usage"
    },
    {
     "expr": "sum by (pod,container)(kube_pod_container_resource_requests{resource=\"memory\",job=\"kubernetes-pods\"} + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0)",
     "legendFormat": "{{pod}} {{container }} requests"
    },
    {
     "expr": "sum by (pod,container)(kube_pod_container_resource_limits{resource=\"memory\",job=\"kubernetes-pods\"} + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0)",
     "legendFormat": "{{pod}} {{container }} limit"
    }
   ]
  },
  {
   "title": "$App Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod,interface,instance)(rate(container_network_receive_bytes_total{}[1m]) + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0) > 0",
     "legendFormat": "{{pod}} {{interface}} {{instance}} receive data"
    },
    {
     "expr": "sum by (pod,interface,instance)(rate(container_network_transmit_bytes_total{}[1m]) + on (pod) group_left(app) up{app=~\"$App\",namespace=~\"$Namespace\",job=\"kubernetes-pods\"} * 0) > 0",
     "legendFormat": "{{pod}} {{interface}} {{instance}} transmit data"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 } },
  {
   "title": "Pod status",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod,namespace)(kube_pod_status_ready{condition=~\"false\",job=\"kubernetes-pods\"} or kube_pod_status_phase{phase=~\"Pending|Unknown|Failed\",job=\"kubernetes-pods\"} == 1)"
    }
   ]
  },
  {
   "title": "Container performance",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod,namespace,container,instance)(rate(container_cpu_usage_seconds_total{container!=\"\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod,namespace,container,instance)(rate(container_memory_working_set_bytes{container!=\"\"}[1m]))"
    },
    {
     "expr": "sum by(pod,namespace,container,instance)(rate(container_fs_writes_bytes_total{container!=\"\"}[1m]))"
    },
    {
     "expr": "sum by(pod,namespace,container,instance)(rate(container_fs_reads_bytes_total{container!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Node performance",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"kubernetes-pods\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"kubernetes-pods\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (100 - ((node_memory_MemAvailable_bytes{job=\"kubernetes-endpoints\"} * 100) / node_memory_MemTotal_bytes{job=\"kubernetes-endpoints\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Positive metrics",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",job=\"kubernetes-pods\"})",
     "legendFormat": "Nodes ready"
    },
    {
     "expr": "sum(kube_pod_status_ready{condition=~\"true\",job=\"kubernetes-pods\"})",
     "legendFormat": "Pods running"
    }
   ]
  },
  {
   "title": "Negative metrics",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (exported_namespace,exported_pod)(kube_pod_container_info{container!=\"\",job=\"kubernetes-pods\"}) unless sum by (exported_namespace,exported_pod)(kube_pod_container_resource_limits{resource=\"cpu\",job=\"kubernetes-pods\"}))",
     "legendFormat": "Containers without CPU limit"
    },
    {
     "expr": "count by (namespace)(sum by (exported_namespace,exported_pod)(kube_pod_container_info{container!=\"\",job=\"kubernetes-pods\"}) unless sum by (exported_namespace,exported_pod)(kube_pod_container_resource_limits{resource=\"memory\",job=\"kubernetes-pods\"}))",
     "legendFormat": "Containers without Memory limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",job=\"kubernetes-pods\"}) - sum(kube_node_status_capacity{resource=\"cpu\",job=\"kubernetes-pods\"})",
     "legendFormat": "CPU limits over capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) - sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "Memory limits over capacity"
    },
    {
     "expr": "sum by(pod,namespace,job)(kube_pod_status_ready{condition=~\"false\",job=\"kubernetes-pods\"} == 1 or kube_pod_status_phase{phase=~\"Pending|Unknown|Failed\",job=\"kubernetes-pods\"} == 1)",
     "legendFormat": "Pods not running"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\",job=\"kubernetes-endpoints\"})",
     "legendFormat": "PVCs Pending"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\",job=\"kubernetes-pods\"})",
     "legendFormat": "Nodes not ready"
    }
   ]
  }
 ]
}