apiVersion: v1
kind: Pod
metadata:
  name: test-observa
  namespace: observa
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "demo.fullname" . }}:{{ .Values.service.port }}']
  restartPolicy: Never