apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: observa
  labels:
    app: alertmanager
spec:
  podManagementPolicy: OrderedReady
  serviceName: alertmanager
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: {{ .Values.alertmanager.image }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yaml"
            - "--storage.path=/data"
          ports:
            - containerPort: 9093
          resources:
            requests:
              cpu: {{ .Values.alertmanager.cpuReq }}
              memory: {{ .Values.alertmanager.memReq }}
            limits:
              cpu: {{ .Values.alertmanager.cpuLim }}
              memory: {{ .Values.alertmanager.memLim }}
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/
            - name: data
              mountPath: /data/
            - name: timezone
              mountPath: /etc/localtime
      restartPolicy: Always
      terminationGracePeriodSeconds: 70
      volumes:
      - name: config
        configMap:
          name: alertmanager
      - name: timezone
        hostPath:
          path: /etc/localtime
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.alertmanager.storage }}