apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: observa
  labels:
    app: alertmanager
spec:
  ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager