apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  namespace: observa
  labels:
    app: blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          fail_if_not_ssl: false
          no_follow_redirects: false
          method: GET
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
          valid_status_codes: []
        prober: http
        timeout: 5s