apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: observa
  labels:
    app: loki
data:
  loki.yaml: | 
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: error

    ingester:
      lifecycler:
        address: 0.0.0.0
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      wal:
        enabled: true
        dir: /loki/wal

    querier:
      max_concurrent: 2048

    query_scheduler:
      max_outstanding_requests_per_tenant: 2048

    frontend:
      address: 0.0.0.0
      max_outstanding_per_tenant: 2048

    compactor:
      working_directory: /loki/retention
      shared_store: filesystem
      compaction_interval: 5m
      retention_enabled: true
      retention_delete_delay: 1h
      retention_delete_worker_count: 100

    schema_config:
      configs:
      - from: 2022-01-01
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
          
    storage_config:
      boltdb:
        directory: /loki/index
      filesystem:
        directory: /loki/chunks

    limits_config:
      enforce_metric_name: false
      retention_period: {{ .Values.loki.retentionTime }}
      reject_old_samples: true
      reject_old_samples_max_age: 24h