apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: observa
  labels:
    app: node-exporter
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: node-exporter
          image: {{ .Values.node_exporter.image }}
          imagePullPolicy: Always
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.node_exporter.cpuReq }}
              memory: {{ .Values.node_exporter.memReq }}
            limits:
              cpu: {{ .Values.node_exporter.cpuLim }}
              memory: {{ .Values.node_exporter.memLim }}
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute