apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: observa
  labels:
    app: node-exporter
spec:
  ports:
    - name: http
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app: node-exporter