apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observa
  labels:
    app: promtail
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/promtail-cm.yaml") . | sha256sum }}
    spec:
      containers:
      - name: promtail
        image: {{ .Values.promtail.image }}
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
          - "-client.url=http://loki:3100/loki/api/v1/push"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: run
          mountPath: /var/run/promtail/
        - name: config
          mountPath: /etc/promtail
        - name: timezone
          mountPath: /etc/localtime
        resources:
          requests:
            cpu: {{ .Values.promtail.cpuReq }}
            memory: {{ .Values.promtail.memReq }}
          limits:
            cpu: {{ .Values.promtail.cpuLim }}
            memory: {{ .Values.promtail.memLim }}
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 0
      terminationGracePeriodSeconds: 10
      volumes:
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: run
        hostPath:
          path: /var/run/promtail/
      - name: config
        configMap:
          name: promtail
      - name: timezone
        hostPath:
          path: /etc/localtime
      serviceAccountName: promtail
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute