apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: observa
  labels:
    app: prometheus
data:
{{ range $path, $bytes := .Files.Glob "prometheus/*.yaml" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4}}
{{ end }}